Refactoring

diff --git a/android-sync b/android-sync
--- a/android-sync
+++ b/android-sync
@@ -62,6 +62,10 @@ dotfiles=(
 )
 
 # Retrives the hostname from the device.
+#
+# Options:
+#   -p PORT         SSH port to use
+#   -t TARGET       Target folder
 get-hostname() {
 	local target
 	local tempfile
@@ -71,12 +75,13 @@ get-hostname() {
 		case "$opt" in
 			t)
 				target="$OPTARG"
+				;;
 		esac
 	done
 
 	tempfile="$(mktemp)"
 
-	myrsync "$target/hostname.txt" "$tempfile" &> /dev/null
+	myrsync -p "$port" "$target/hostname.txt" "$tempfile" &> /dev/null
 
 	cat "$tempfile"
 	
@@ -118,19 +123,59 @@ gather-colorcodes() {
 
 # Wrapper for rsync with all the options.
 #
-# :param: A list with more parameters for rsync.
+# Options:
+#   -p PORT         Port for SSH
+#
+# Positional arguments:
+#   OPTIONS         other rsync options and arguments
 myrsync() {
+	local port
+
+	while getopts "p:" opt
+	do
+		case "$opt" in
+			p)
+				port="$OPTARG"
+				;;
+		esac
+	done
+
 	rsync --rsh="ssh -p $port" --progress -hlmrv --size-only --ignore-errors \
 		"$@"
 }
 
 # Copies a folder with PDFs to the device.
 #
-# :param: Folder to copy.
+# Options:
+#   -b BASE         base on the computer
+#   -p PORT         Port for SSH
+#   -t TARGET       target folder on device
+#
+# Positional arguments:
+#   FROM            folder on the computer
 copy-single-pdf-folder() {
-	local from="$1"
-	local frombase="${from#/home/*/}"
-	local target="$target_pdf/${frombase%/*}"
+	local from
+	local frombase
+	local target
+
+	while getopts "b:p:t:" opt
+	do
+		case "$opt" in
+			b)
+				frombase="$OPTARG"
+				;;
+			p)
+				port="$OPTARG"
+				;;
+			t)
+				target="$OPTARG"
+				;;
+		esac
+	done
+
+	from="$1"
+	frombase="${from#/home/*/}"
+	target="$target_pdf/${frombase%/*}"
 
 	echo "${cyan}Folder $from to $target${reset}"
 
@@ -143,19 +188,46 @@ copy-single-pdf-folder() {
 
 # Moves a given folder to the dropfolder.
 #
-# :param: Folder on the remote device.
+# Options:
+#   -d DROPFOLDER   folder on computer
+#   -p PORT         port for SSH
+#   -t TARGET       target folder on device
+#
+# Positional arguments:
+#   FOLDER          folder on the remote device
 move-to-computer() {
+	local dropfolder
+	local folder
+	local port
+	local target
+
 	folder="$1"
+
+	while getopts "d:p:t:" opt
+	do
+		case "$opt" in
+			d)
+				dropfolder="$OPTARG"
+				;;
+			p)
+				port="$OPTARG"
+				;;
+			t)
+				target="$OPTARG"
+				;;
+		esac
+	done
 
 	print-heading "move $folder to computer"
 
-	myrsync -b "$target/$folder/" "$dropfolder"
-	ssh -p 2222 "$ip" "rm -frv /sdcard/$folder/*"
+	myrsync -p "$port" -b "$target/$folder/" "$dropfolder"
+	ssh -p "$port" "$ip" "rm -frv /sdcard/$folder/*"
 }
 
 # Prints a colored heading.
 #
-# :param: Heading text.
+# Positional arguments
+#   TEXT            text to print
 print-heading() {
 	echo
 	echo "${green}$1${reset}"
@@ -174,37 +246,92 @@ print-nexus() {
 
 # Checks whether the given host is reachable.
 #
-# :returns: the exit status of ping
+# Positional arguments:
+#   IP              IP address to check
+#
+# Exit status:
+#   the exit status of ping
 ping-test() {
-	ping -c 1 -w 1 "$ip" &> /dev/null
+	ping -c 1 -w 1 "$1" &> /dev/null
 }
 
 # Copies dotfiles to the remote device.
 copy-dotfiles() {
-	myrsync "${dotfiles[@]}" "$target/"
+	myrsync -p "$port" "${dotfiles[@]}" "$target/"
 }
 
 # copies PDF files to the device using ``copy-single-pdf-folder``.
 copy-pdffiles() {
 	print-heading "copying PDF files to device"
-	for pdfdir in "${pdfdirs[@]}"
+
+	for pdfdir
 	do
-		copy-single-pdf-folder "$pdfdir"
+		copy-single-pdf-folder -p "$port" "$pdfdir"
 	done
 }
 
 # Copies the contents of the bins using ``move-to-computer``.
+#
+# Options:
+#   -d DROPFOLDER   folder on computer
+#   -p PORT         port for SSH
+#   -t TARGET       target folder on device
+#
+# Positional arguments:
+#   BIN ...         bins to empty
 copy-bins() {
-	for bin in "${bins[@]}"
+	local dropfolder
+	local folder
+	local port
+	local target
+
+	folder="$1"
+
+	while getopts "d:p:t:" opt
 	do
-		move-to-computer "$bin"
+		case "$opt" in
+			d)
+				dropfolder="$OPTARG"
+				;;
+			p)
+				port="$OPTARG"
+				;;
+			t)
+				target="$OPTARG"
+				;;
+		esac
+	done
+
+	for bin
+	do
+		move-to-computer -d "$dropfolder" -p "$port" -t "$target" "$bin"
 	done
 }
 
 # Copies all the music to the device.
+#
+# Options:
+#   -p PORT         SSH port to use
+#
+# Positional arguments:
+#   TARGET          Target folder
 copy-music() {
+	local port
+	local target_music
+
+	while getopts "p:" opt
+	do
+		case "$opt" in
+			p)
+				port="$OPTARG"
+				;;
+		esac
+	done
+
+	target_music="$1"
+
 	print-heading "Copying MP3 files to device"
-	myrsync --delete --max-size 15M \
+	myrsync -p "$port" --delete --max-size 15M \
 		--force --exclude-from "/home/mu/.config/syncscripts/handy_musik.txt" \
 		"/home/mu/.cache/mp3_packer/128/home/mu/Musik/Musik/" "$target_music/"
 }
@@ -213,15 +340,35 @@ copy-music() {
 # the files that are copied from the device have their permissions preserved.
 # Since the user ID is different, the user who calls this script does not have
 # permissions on the files and folders.
+#
+# Positional arguments:
+#   DROPFOLDER      folder on computer
 fix-permissions() {
+	local dropfolder
+
+	dropfolder="$1"
+
 	print-heading "Fix permissions in $dropfolder"
 	find "$dropfolder" -type d -exec chmod u+rwx '{}' \;
 	find "$dropfolder" -type f -exec chmod u+rw '{}' \;
 }
 
 # Performs the syncing. This functions pretty much calls all other functions.
+#
+# Positional arguments
+#   IP              IP address of the device
 sync-device() {
-	if ! ping-test
+	local dropfolder
+	local hostname
+	local ip
+	local port
+	local target
+	local target_music
+	local target_pdf
+
+	ip="$1"
+
+	if ! ping-test "$ip"
 	then
 		echo "${red}Device is not reachable. Aborting.${reset}"
 		return
@@ -236,17 +383,14 @@ sync-device() {
 
 	hostname="$(get-hostname -t "$target")"
 
-	echo "$hostname"
-	exit
-
 	echo "${bold}Syncing $hostname @ $ip${reset}"
 
-	copy-bins
-	copy-dotfiles
-	copy-pdffiles
-	copy-music
+	copy-bins -d "$dropfolder" -p "$port" -t "$target" "${bins[@]}"
+	copy-dotfiles -p "$port" "${dotfiles[@]}"
+	copy-pdffiles -p "$port" "${pdfdirs[@]}"
+	copy-music -p "$port"
 
-	fix-permissions
+	fix-permissions "$dropfolder"
 
 	backup-status update "$hostname"
 }
@@ -255,12 +399,11 @@ gather-colorcodes
 
 if [[ -n "${1:-}" ]]
 then
-	ip="$1"
-	sync-device
+	sync-device "$1"
 else
 	for ip in "${ips[@]}"
 	do
-		if ! sync-device
+		if ! sync-device "$ip"
 		then
 			echo "Failed."
 		fi
